# Generated by Django 5.1.6 on 2026-06-22 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', '-completed_at'], name='pomodoro_po_user_id_9e03f1_idx'),
        ),
    ]
